apiVersion: v1
kind: Service
metadata:
  name: java-tomcat-service
  labels:
    app: java-tomcat
spec:
  selector:
    app: java-tomcat
  ports:
    - protocol: TCP
      port: 80        # External port to expose
      targetPort: 8080 # Port on the container
  type: LoadBalancer  # Type can be ClusterIP, NodePort, or LoadBalancer
